<script>
            function szChange(value){
            if(value == 'pp' || value == 'PP') {
                return true;
            }
            
            window.location.href = 'https://p-tweets.com/talk/feed?cat_id=' + value;
            
        }
</script>
<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="cp h-mobile" style="margin-bottom: 10px;">
			<a href="<?php echo cl_link("/"); ?>">
				<img src="{%config site_logo%}" alt="Logo">
				<h1 class="ml11">
					<span class="text-wrapper">
						<span class="line line1"></span>
						<span class="letters">{%config name%}</span>
					</span>
				</h1>
			</a>
		</div>
		<div class="sidebar-v-nav-wrapper">
			<ul class="sidebar-v-nav">
				<li data-navitem="home" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'feed' && !isset($_GET['cat_id'])) {
																		echo ('active');
																	} ?>">
					<span class="icon home">
					    <a href="<?php echo cl_link('/'); ?>" >
						<?php echo cl_ikon('home'); ?>
						</a>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('/'); ?>" >
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="explore" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore' && $cl["page_tab"] !== 'categories') {
																		echo ('active');
																	} ?>">
					<span class="icon">
					    <a href="<?php echo cl_link("explore"); ?>" >
						<?php echo cl_ikon('explore'); ?>
						</a>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("explore"); ?>" >
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="explore" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') {
																		
																	} ?>">
					<span class="icon">
					    <a href="<?php echo cl_link("explore/categories"); ?>" >
						<svg fill="#000000" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
                        	 width="800px" height="800px" viewBox="0 0 36.09 36.09" xml:space="preserve"
                        	>
                        <g>
                        	<path d="M36.042,13.909c-0.123-0.377-0.456-0.646-0.85-0.688l-11.549-1.172L18.96,1.43c-0.16-0.36-0.519-0.596-0.915-0.596
                        		s-0.755,0.234-0.915,0.598L12.446,12.05L0.899,13.221c-0.394,0.04-0.728,0.312-0.85,0.688c-0.123,0.377-0.011,0.791,0.285,1.055
                        		l8.652,7.738L6.533,34.045c-0.083,0.387,0.069,0.787,0.39,1.02c0.175,0.127,0.381,0.191,0.588,0.191
                        		c0.173,0,0.347-0.045,0.503-0.137l10.032-5.84l10.03,5.84c0.342,0.197,0.77,0.178,1.091-0.059c0.32-0.229,0.474-0.633,0.391-1.02
                        		l-2.453-11.344l8.653-7.737C36.052,14.699,36.165,14.285,36.042,13.909z M25.336,21.598c-0.268,0.24-0.387,0.605-0.311,0.957
                        		l2.097,9.695l-8.574-4.99c-0.311-0.182-0.695-0.182-1.006,0l-8.576,4.99l2.097-9.695c0.076-0.352-0.043-0.717-0.311-0.957
                        		l-7.396-6.613l9.87-1.002c0.358-0.035,0.668-0.264,0.814-0.592l4.004-9.077l4.003,9.077c0.146,0.328,0.456,0.557,0.814,0.592
                        		l9.87,1.002L25.336,21.598z"/>
                        </g>
                        </svg>
                        </a>
					</span>
					<span class="nav-item-holder">
						<!--<a href="<?php echo cl_link("explore"); ?>" >-->
						<!--	<?php echo cl_translate('Categories'); ?>-->
						<!--</a>-->
						
                            <select id="categorySelect" class="categorySelect szLeftCate" onchange="szChange(this.value)" style="/* padding: 10px; */overflow: scroll !important;text-align: left;margin-left: -2px;overflow: hidden;width: 11rem; <?php if(isset($_GET['cat_id']) || $cl["page_tab"] == 'categories') { echo 'font-weight: bold;'; }  ?>">
                                 <option value="PP">Categories</option>
    								<?php
							
								$mysqli = new mysqli('localhost', 'tweetsp_talkus', 'Kiwm&@mkeIW212', 'tweetsp_talk');
								$db = new MysqliDb($mysqli);
								
								    // require_once(cl_full_path('core/web_req_init.php'));
								    require_once(cl_full_path("core/apps/home/app_ctrl.php"));
								    
								    
                                        $categories = $db->rawQuery("SELECT * FROM cl_categories WHERE parent_id IS NULL  order by name ASC ;");
                                    
                                        foreach ($categories as $k => $cat) {
                                            
                                            $subcategories = $db->rawQuery("SELECT * FROM `cl_categories` WHERE parent_id = " . $cat['id'] . " order by name ASC");
                                            
                                                // if(count($subcategories) > 0){
                                                //     echo '<option value="PP">'.$cat['name'].'</option>';
                                                // }else{
                                                //     echo '<option value="'.$cat['id'].'">'.$cat['name'].'</option>';
                                                // }
                                        
                                        
                                               echo '<option value="'.$cat['id'].'">'.$cat['name'].'</option>';
                                                
                									
                    							 
                                                if(count($subcategories) > 0) {
                                                        foreach ($subcategories as $subcategory) {
                                                            echo '<option value="'.$subcategory['id'].'">&nbsp;&nbsp;&nbsp;'.$subcategory['name'].'</option>';
                                                        }
                                                }
                							  
                                        
                                            
                                        }
                                    
								
								?>
</select>
						
					</span>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="guest_bottom">
	<div class="r-o96wvk"></div>
	<div class="guest_login">
		<div class="login_txt">
			<h1><?php echo cl_translate("dont_miss"); ?></h1>
			<h6><?php echo cl_translate("dont_miss_desc", array(
						"site_name" => $cl["config"]["name"]
					)); ?></h6>
		</div>
		<div class="login_btn">
			<button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#loginModal"><?php echo cl_translate("Log in"); ?></button>
			<button type="button" class="btn btn-light" data-toggle="modal" data-target="#signupModal"><?php echo cl_translate("Sign up"); ?></button>


		</div>
	</div>
</div>
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/login'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Sign Up Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/register'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Forgot Modal -->
<div class="modal fade" id="forgotModal" tabindex="-1" aria-labelledby="forgotModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/reset_password'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php echo cl_template('auth/scripts/app_master_script'); ?>



