<?php error_reporting(E_ALL & ~E_NOTICE); ?>


<?php if ( isset($cl['li']['advertising']) && !empty(($cl['li']['advertising']))): ?>
	<?php echo cl_template('timeline/ad'); ?>
<?php else: ?>
    <?
    $catId  = $cl['li']['cat_id'] ?? 0;
    ?>
    <?php if (isset($_GET['cat_id'])): ?>
    
     <?php if (($_GET['cat_id']) == $catId): ?>
        <?php echo cl_template('timeline/post_inner'); ?>
     <?php endif; ?>
        
    <?php else: ?>
       
        <?php echo cl_template('timeline/post_inner'); ?>
    <?php endif; ?>
        
    
<?php endif; ?>