<div class="cp-app-container" data-app="about_settings">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3>Sub Categories Page </h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>">                                    <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item">    <?php echo cl_translate('Categories'); ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card"  style="padding: 15px;">
                    <div class="card-header">
                        <h5>
                            Manage Sub Categories
                        </h5>
                    </div>

                    <div class="vueCat">
                        <button type="button" v-on:click="addCategory()" class="btn btn-primary">Add New</button>
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Parent Name</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-if="loading">
                                <td colspan="3"><i class="fa fa-spinner fa-spin"></i></td>
                            </tr>
                            <tr v-for="(cat, id) in categories">
                                <td>{{id+1}}</td>
                                <td>{{cat.name}}</td>
                                <td>{{cat.parent_name}}</td>
                                <td>
                                    <a href="Javascript:;" v-on:click="editCategory(cat)">Edit</a> |
                                    <a href="Javascript:;" v-on:click="deleteCategory(cat)">Delete</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>



                        <!-- The Modal -->
                        <div class="modal" id="myModal">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Edit Category</h4>
                                        <button type="button" class="close" @click="$('#myModal').modal('hide')">&times;</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="name">Name:</label>
                                            <input type="text" class="form-control" placeholder="Enter name" id="name" v-model='selectedCategory.name' >
                                        </div>
                                        <div class="form-group">
                                            <label for="name">Parent Category:</label>
                                            <select class="form-control" v-if="parent_categories"  v-model='selectedCategory.parent_id'>
                                                <option v-for="c in parent_categories" :value="c.id">{{c.name}}</option>
                                            </select>
                                        </div>

                                        <button type="button" v-on:click="updateCategory()" class="btn btn-primary">Update</button>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <!-- The Modal -->
                        <div class="modal" id="addCategoryModal">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Add Category</h4>
                                        <button type="button" class="close" @click="$('#addCategoryModal').modal('hide')">&times;</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="name">Name:</label>
                                            <input type="text" class="form-control" placeholder="Enter name" id="name" v-model='addObj.name' >
                                        </div>
                                        <div class="form-group">
                                            <label for="name">Parent Category:</label>
                                            <select class="form-control" v-if="parent_categories"  v-model='addObj.parent_id'>
                                                <option v-for="c in parent_categories" :value="c.id">{{c.name}}</option>
                                            </select>
                                        </div>
                                        <button type="button" v-on:click="addCategoryPost()" class="btn btn-primary">Add</button>
                                    </div>

                                    <!-- Modal footer -->
                                    <!--<div class="modal-footer">-->
                                    <!--  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>-->
                                    <!--</div>-->

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/sub_categories_pages/scripts/app_master_script'); ?>
