<div class="cp-app-container" data-app="ads-settings">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('Advertisement account settings'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('Advertisement account settings'); ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="d-block" id="vue-cpanel-users-app">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card" style="padding: 15px;">
                        <div class="card-header">
                            <h5>
                                <?php echo cl_translate('Manage advertisement account system settings'); ?>
                            </h5>
                        </div>
                        <div class="card-body">
                            <form class="form" data-an="form">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group" data-an="advertisement_mprice-input">
                                            <label>
                                                <?php echo cl_translate('Advertisement monthly price'); ?> (<b><?php echo strtoupper($cl["config"]["site_currency"]); ?></b>)
                                            </label>
                                            <div class="form-line">
                                                <input value="{%config advertisement_mprice%}" name="advertisement_mprice" type="text" class="form-control" placeholder="PremiE.g. 10">
                                            </div>
                                            <div class="alert alert-light dark m-15" role="alert">
                                                <p>
                                                    <?php echo cl_translate('account_monthly_price_help'); ?>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group" data-an="advertisement_yprice-input">
                                            <label>
                                                <?php echo cl_translate('advertisement annually price'); ?> (<b><?php echo strtoupper($cl["config"]["site_currency"]); ?></b>)
                                            </label>
                                            <div class="form-line">
                                                <input value="{%config advertisement_yprice%}" name="advertisement_yprice" type="text" class="form-control" placeholder="PremiE.g. 10">
                                            </div>
                                            <div class="alert alert-light dark m-15" role="alert">
                                                <p>
                                                    <?php echo cl_translate('account_monthly_price_help'); ?>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group" data-an="advertising_system-input">
                                            <label>
                                                Advertising system
                                            </label>
                                            <div class="input-group"><span class="input-group-text"><i class="icofont icofont-toggle-on"></i></span>
                                                <select name="advertising_system" class="form-select form-control-primary">
                                                    <option value="on" <?php if ($cl['config']['advertising_system'] == 'on') {
                                                                            echo ('selected');
                                                                        } ?>>
                                                        <?php echo cl_translate('Enabled'); ?>
                                                    </option>
                                                    <option value="off" <?php if ($cl['config']['advertising_system'] == 'off') {
                                                                            echo ('selected');
                                                                        } ?>>
                                                        <?php echo cl_translate('Disabled'); ?>
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 no-mb">
                                        <button class="btn btn-primary" type="submit" data-an="submit-ctrl">
                                            <?php echo cl_translate("Save changes"); ?>
                                        </button>
                                    </div>
                                </div>
                                <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/ads_settings/scripts/app_master_script'); ?>