
<?php 
error_reporting(E_ALL & ~E_NOTICE);
?>
<!--keston 0139-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
<style>
body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-placeholder div.icon2 {
			line-height: 0px;
			margin-bottom: 35px;
			width: 100%;
			text-align: center;
		}

		.terms {

			font-size: 12px;
			margin-top: 20px;

		}

        .highlighted-plan {
            display: inline-block;
            padding: 5px 10px;
            border: 2px solid #007bff;  /* Blue border */
            background-color: #f0f8ff;  /* Light blue background */
            border-radius: 5px;         /* Rounded corners */
            font-weight: bold;          /* Bold text */
        }
		.blue_desc .help {
			text-align: left !important;
			margin-left: 40px !important;
		}

		.blue_desc span svg {
			margin-right: 12px;
			color: var(--cl-primary-text-color);
			position: relative;
			max-width: 100%;
			height: 1.25em;
			fill: currentcolor;
			display: inline-block;
			font-size: 15px;
		}

		.pl-message {
			margin-top: 30px;
		}

		.nav-tabs {

			border-bottom-color: var(--smc-main-border-color);
			border-bottom-style: solid;
			border-bottom-width: 1px;
		}

		.nav-fill .nav-item .nav-link,
		.nav-justified .nav-item .nav-link {
			width: auto;
			text-decoration: none;
			text-transform: none;
			color: var(--smc-main-text-color-lighten-5);
			font-weight: 500;
			font-size: 15px;
		}

		.nav-tabs .nav-item.show .nav-link,
		.nav-tabs .nav-link.active {
			color: var(--smc-main-text-color);
			border-bottom-color: var(--smc-main-border-color);
			border-bottom-width: 1px;
			font-weight: 700;
			background: transparent;
		}

		.nav-tabs .nav-item.show .nav-link,
		.nav-tabs .nav-link.active div.css-1dbjc4n {
			background-color: rgb(29, 155, 240);
			height: 4px;
			width: 56px;
			border-radius: 9999px;
			text-align: center;
			display: block;
			position: relative;
			bottom: 0;
			margin-left: auto;
			margin-right: auto;
			margin-top: 15px;
			margin-bottom: -15px;
		}

		div.icon2 img {
			width: 150px;
			height: auto;
			margin-bottom: 0px;
			margin-top: -30px;
		}

		div.icon2 {
			text-align: center;
		}
		.h-mobile{
	        width: max-content !important;
	    }


</style>
<div class="timeline-container" data-app="thread">
	<div class="timeline-header" data-el="tl-header">
		<div class="lp" style="display: inline-flex;">
			<!--onclick="SMColibri.go_back();-->
			<a  href="https://p-tweets.com/talk" class="go-back"><?php echo cl_ikon('arrow-left'); ?></a>
			<div class="nav-link-holder">
				<a href="<?php echo $cl['thread_data']['post']['url']; ?>" data-spa="true">
					<?php echo cl_translate("Ad"); ?>
				</a>
			</div>
		</div>
		<div class="cp">
		</div>
		<div class="rp">
		</div>
	</div>
	
	<!--keston plan add-->
	
	<div class="ads-management">	
		<div class="ads-management__upsert">
			<form class="form" id="vue-ads-upsert-expire-app" autocomplete="off">						
				<div class="form-group px-4">
						<?php if ($cl['thread_data']['post']['timeleft'] <= 7 && $cl['thread_data']['post']['owner']['username'] == $me['username']) : ?>
							<!-- Subscription Section Start -->
							<div class="form-group">
								<div class="pl-message">
									<h6 class="form-info-label text-center text-danger mt-3">
										<?php echo cl_translate("Don't Miss Out – Renew Your AD for Continued Exposure!"); ?>
									</h6>
									<?php if ($cl['thread_data']['post']['timeleft'] > 0 && $cl['thread_data']['post']['owner']['username'] == $me['username']) : ?>
										<div class = "form-info-label text-center text-danger mt-3">
											Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is about to expire in <?php echo $cl['thread_data']['post']['timeleft']; ?> days.
										</div>
									<?php else: ?>
										<div class = "form-info-label text-center text-danger mt-3">
											Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is expired!
										</div>
									<?php endif; ?>
								</div>
							</div>
					        <div class="form-group mb-0">
                                <label><?php echo cl_translate("Ad Plans - Ads are approved in"); ?>
                                    <span class="text-danger" style="font-size: 14px;">
                                        <?php echo cl_translate(" 48 hours"); ?>
                                    </span>
                                    <?php echo cl_translate(". If your Ad is not approved you will receive an email for the next step."); ?>
                                </label>
                                <div class="d-flex justify-content-between">
                                    <!-- Radio button for Yearly Plan -->
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" id="yearlyPlan" v-model="selectedPlan" value="yearly">
                                        <label class="form-check-label" for="yearlyPlan">
                                            <?php echo cl_translate("Yearly Plan (365 days)"); ?> - <span style="font-size: 14px; color: green;">{{ yearlyPrice }}/Year</span>
                                        </label>
                                    </div>
                            
                                    <!-- Radio button for Monthly Plan -->
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" id="monthlyPlan" v-model="selectedPlan" value="monthly">
                                        <label class="form-check-label" for="monthlyPlan">
                                            <?php echo cl_translate("Monthly Plan (30 days)"); ?> - <span style="font-size: 14px; color: green;">{{ monthlyPrice }}/Month</span>
                                        </label>
                                    </div>
                                </div>
                            
                                <!-- Dynamic Description based on selected plan -->
                                <div v-if="selectedPlan === 'monthly'" class="pl-message">
                                    <h6 class="form-info-label text-center">
                                        <?php echo cl_translate('Create a Monthly Ad Plan'); ?>
                                    </h6>
                                    <div class="pb-2 form-info-label text-center">
                                        <?php echo cl_translate("Your ad will be displayed for one month. Ideal for short-term promotions."); ?>
                                    </div>
                                </div>
                            
                                <div v-if="selectedPlan === 'yearly'" class="pl-message">
                                    <h6 class="form-info-label text-center">
                                        <?php echo cl_translate('Create a Yearly Ad Plan'); ?>
                                    </h6>
                                    <div class="pb-2 form-info-label text-center">
                                        <?php echo cl_translate("Your ad will be displayed for a full year. Perfect for long-term campaigns."); ?>
                                    </div>
                                </div>
                            </div>
                            <!-- Show selected subscription if any -->
                            <div class="form-group text-center" v-if="selectedPlan">
                                <label><?php echo cl_translate("Selected Plan : "); ?><span class="highlighted-plan">{{selectedPlanText}}</span></label>
                            </div>  
                            <!-- Subscription Section End -->
                    		<div class="form-group">
                    			<div class="form-tos">
                    				<div class="form-check">
                    					<input v-model="tos_agree" id="tos-agree" type="checkbox" class="form-check-input">
                    					<label for="tos-agree" class="form-check-label">
                    						<span>
                    							<?php echo cl_translate("By continuing, you agree to {@site_name@}",array(
                    								"site_name" => $cl["config"]["name"]
                    							)); ?>
                    						</span>
                    						<a href="<?php echo cl_link('terms_of_use'); ?>"><?php echo cl_translate("Terms of Use"); ?></a> <?php echo cl_translate("And"); ?> <a href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>
                    					</label>
                    				</div>
                    			</div>
                    		</div>
                    		<div class="form-group">
                    			<button v-if="submitting" disabled="true" class="btn btn-custom main-inline lg btn-block">
                    				<?php echo cl_translate("Please wait"); ?>
                    			</button>
                    			<button v-else v-bind:disabled="!selectedPlan || !tos_agree" type="button" class="btn btn-custom main-inline lg btn-block" @click="publish">
                					<?php echo cl_translate("Publish"); ?>
                    			</button>
                    		</div>
						<?php endif; ?>
				</div>
			</form>
		</div>
	</div>
	<!--keston plan add-->
	<div class="publication--thread-container">
		<div class="publication--thread-container-inner">
			<?php if (not_empty($cl['thread_data']['parent'])): ?>
				<div class="publication--thread-chain-holder">
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls" data-an="chain-list">
							<?php foreach ($cl['thread_data']['parent'] as $cl["li"]): ?>
								<?php echo cl_template('timeline/post'); ?>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
			<?php endif; ?>
			
			<?php if (not_empty($cl["gads_horiz"])): ?>
				<div class="cl-google-ads centered">
					<?php echo $cl["gads_horiz"]; ?>
				</div>
			<?php endif; ?>
			<!--Hide reply thread holder 2025.04.11 by keston-->
			<!--////////////////////////////////////////////-->
			<?php if (not_empty($cl["random_ads"])): ?>
				<div class="timeline-posts-container">
					<div class="timeline-posts-ls szHomeTimeline" data-an="entry-list">
						<?php foreach ($cl["random_ads"] as $cl['li']): ?>
							<?php echo cl_template('timeline/ad'); ?>
						<?php endforeach; ?>
					</div>
				</div>
			<?php else: ?>
                <div class="no-ads-message">
                    <p>No ads available.</p>
                </div>
			<?php endif; ?>
			
			<!--///////////////////////-->
			<div class="publication--thread-replys-holder">
				<?php if (not_empty($cl['thread_data']['next'])): ?>
					<!--<div class="timeline-posts-container">-->
					<!--	<div class="timeline-posts-ls" data-an="replys-list">-->
					<!--		<?php foreach ($cl['thread_data']['next'] as $cl["li"]): ?>-->
					<!--			<?php if (empty($cl["li"]["replys"])): ?>-->
					<!--				<?php echo cl_template('timeline/post'); ?>-->
					<!--			<?php else: ?>-->
					<!--				<div class="timeline-posts-ls-group">-->
					<!--					<div class="timeline-posts-ls-group-inner">-->
					<!--						<?php echo cl_template('timeline/post'); ?>-->

					<!--						<?php $parent_thread = $cl['li']; $post_replys = $parent_thread['replys']; $post_replys = array_reverse($post_replys); foreach ($post_replys as $cl['li']) { echo cl_template('timeline/post');} ?>-->
					<!--					</div>-->

					<!--					<a class="show-thread" href="<?php echo ($parent_thread["url"]); ?>" data-spa="true">-->
					<!--						<span class="txt-label">-->
					<!--							(-->
					<!--							<?php echo ($parent_thread["replys_count"]); ?>)-->
					<!--							<?php echo cl_translate("Show this thread"); ?>-->
					<!--						</span>-->
					<!--						<span class="icon">-->
					<!--							<?php echo cl_ikon('arrow-right'); ?>-->
					<!--						</span>-->
					<!--					</a>-->
					<!--				</div>-->
					<!--			<?php endif; ?>-->
					<!--		<?php endforeach; ?>-->
					<!--	</div>-->
					<!--</div>-->
					<?php if (count($cl['thread_data']['next']) == 30): ?>
						<!--<div class="load-more">-->
						<!--	<button class="btn btn-custom main-outline lg" data-an="load-more">-->
						<!--		<?php echo cl_translate("Show more"); ?>-->
						<!--	</button>-->
						<!--</div>-->
					<?php else: ?>
						<!--<div class="load-more">-->
						<!--	<button disabled="true" class="btn btn-custom main-outline lg" data-an="load-more">-->
						<!--		<?php echo cl_translate("That is all for now!"); ?>-->
						<!--	</button>-->
						<!--</div>-->
					<?php endif; ?>
				<?php else: ?>
					<!--<div class="no-thread-replys">-->
					<!--	<div class="icon">-->
					<!--		<?php echo cl_ikon('chat-post'); ?>-->
					<!--	</div>-->
					<!--	<div class="pl-message">-->
					<!--		<h4>-->
					<!--			<?php echo cl_translate("No replys yet!"); ?>-->
					<!--		</h4>-->
							<!--<p>-->
								<!--<?php echo cl_translate("It seems that this publication does not yet have any comments. In order to respond to this publication from {@publisher_name@}, click on at the button above", array("svg_icon" => cl_html_el("span", cl_ikon('chat-post')), "publisher_name" => cl_html_el('a', $cl['thread_data']['post']['owner']['name'], array("href" => $cl['thread_data']['post']['owner']['url'],"data-spa" => "true")))); ?>-->
							<!--</p>-->
					<!--	</div>-->
					<!--</div>-->
				<?php endif; ?>
			</div>
		</div>
	</div>
	<?php echo cl_template('thread/scripts/app_master_script'); ?>
</div>

<style>
	body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-header div.lp div.nav-link-holder {
		line-height: 20px;
		display: inline-flex;
		margin: ;
		vertical-align: middle;
		justify-content: center;
		align-items: center;
	}

	.reply_button button.btn-custom.reply {
		max-height: 36px !important;
		min-height: 36px !important;
		color: rgb(255, 255, 255);
		font-weight: 700;
		-moz-box-align: center;
		align-items: center;
		-moz-box-pack: center;
		justify-content: center;
		font-size: 15px !important;
		display: flex;
		background-color: rgb(29, 155, 240) !important;
		transition-property: background-color, box-shadow !important;
		border-color: rgba(0, 0, 0, 0) !important;
		padding-left: 16px !important;
		padding-right: 16px !important;
		border-width: 1px;
		border-style: solid;
	}
</style>