<!--keston 0139-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
<style>
body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-placeholder div.icon2 {
			line-height: 0px;
			margin-bottom: 35px;
			width: 100%;
			text-align: center;
		}

		.terms {

			font-size: 12px;
			margin-top: 20px;

		}

		.blue_desc .help {
			text-align: left !important;
			margin-left: 40px !important;
		}

		.blue_desc span svg {
			margin-right: 12px;
			color: var(--cl-primary-text-color);
			position: relative;
			max-width: 100%;
			height: 1.25em;
			fill: currentcolor;
			display: inline-block;
			font-size: 15px;
		}

		.pl-message {
			margin-top: 30px;
		}

		.nav-tabs {

			border-bottom-color: var(--smc-main-border-color);
			border-bottom-style: solid;
			border-bottom-width: 1px;
		}

		.nav-fill .nav-item .nav-link,
		.nav-justified .nav-item .nav-link {
			width: auto;
			text-decoration: none;
			text-transform: none;
			color: var(--smc-main-text-color-lighten-5);
			font-weight: 500;
			font-size: 15px;
		}

		.nav-tabs .nav-item.show .nav-link,
		.nav-tabs .nav-link.active {
			color: var(--smc-main-text-color);
			border-bottom-color: var(--smc-main-border-color);
			border-bottom-width: 1px;
			font-weight: 700;
			background: transparent;
		}

		.nav-tabs .nav-item.show .nav-link,
		.nav-tabs .nav-link.active div.css-1dbjc4n {
			background-color: rgb(29, 155, 240);
			height: 4px;
			width: 56px;
			border-radius: 9999px;
			text-align: center;
			display: block;
			position: relative;
			bottom: 0;
			margin-left: auto;
			margin-right: auto;
			margin-top: 15px;
			margin-bottom: -15px;

		}

		div.icon2 img {
			width: 150px;
			height: auto;
			margin-bottom: 0px;
			margin-top: -30px;
		}

		div.icon2 {
			text-align: center;
		}
		.h-mobile{
	        width: max-content !important;
	    }


</style>
<div class="timeline-container" data-app="thread">
	<div class="timeline-header" data-el="tl-header">
		<div class="lp" style="display: inline-flex;">
			<span class="go-back" onclick="SMColibri.go_back();">
				<?php echo cl_ikon('arrow-left'); ?>
			</span>
			<div class="nav-link-holder">
				<a href="<?php echo $cl['thread_data']['post']['url']; ?>" data-spa="true">
					<?php echo cl_translate("Ad"); ?>
				</a>
			</div>
		</div>
		<div class="cp">
		</div>
		<div class="rp">
		</div>
	</div>
	
	<!--keston plan add-->
	
	<div class="ads-management">	
		<div class="ads-management__upsert">
			<form class="form" id="vue-ads-upsert-expire-app" autocomplete="off">						
				<div class="form-group">
						<?php if ($cl['thread_data']['post']['timeleft'] <= 7 && $cl['thread_data']['post']['owner']['username'] == $me['username']) : ?>
							<!-- Subscription Section Start -->
							<div class="form-group">
								<ul class="nav nav-tabs nav-justified mb-3" id="adSubscriptionTab" role="tablist">
									<li class="nav-item" role="presentation">
										<a class="nav-link active" id="yearly-tab" data-toggle="tab" href="#yearly" role="tab"
											aria-controls="yearly" aria-selected="true">
											<?php echo cl_translate("Yearly Plan (365 days) "); ?>
										</a>
									</li>
									<li class="nav-item" role="presentation">
										<a class="nav-link" id="monthly-tab" data-toggle="tab" href="#monthly" role="tab"
											aria-controls="monthly" aria-selected="false">
											<?php echo cl_translate("Monthly Plan (30 days) "); ?>
										</a>
									</li>
								</ul>
								<div class="tab-content" id="adSubscriptionTabContent">
									<!-- Yearly Subscription -->
									<div class="tab-pane fade show active" id="yearly" role="tabpanel" aria-labelledby="yearly-tab">
										<div class="pl-message">
											<h6 class="form-info-label text-center text-danger mt-3">
												<?php echo cl_translate("Don't Miss Out – Renew Your AD for Continued Exposure!"); ?>
											</h6>
											<?php if ($cl['thread_data']['post']['timeleft'] > 0 && $cl['thread_data']['post']['owner']['username'] == $me['username']) : ?>
												<div class = "form-info-label text-center text-danger mt-3">
													Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is about to expire in <?php echo $cl['thread_data']['post']['timeleft']; ?> days.
												</div>
											<?php else: ?>
												<div class = "form-info-label text-center text-danger mt-3">
													Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is expired!
												</div>
											<?php endif; ?>
											<h6 class="form-info-label text-center">
												<?php echo cl_translate('Continue a Yearly Ad Plan'); ?></h6>
											<div class="pb-2 form-info-label text-center">
												<?php echo cl_translate("Your ad will be displayed for a full year. Perfect for long-term campaigns."); ?>
											</div>
										</div>
										<div class="d-flex justify-content-center text-center c2action-single">
											<button type="button" class="btn btn-custom main-inline lg btn-block  w-50"
												v-on:click="selectPlan('yearly')">
												{{ selectYearlyText }}
											</button>
										</div>
									</div>
									<!-- Monthly Subscription -->
									<div class="tab-pane fade" id="monthly" role="tabpanel" aria-labelledby="monthly-tab">
										<div class="pl-message">
											<h6 class="form-info-label text-center text-danger mt-3">
												<?php echo cl_translate("Don't Miss Out – Renew Your AD for Continued Exposure!"); ?>
											</h6>
											<?php if ($cl['thread_data']['post']['timeleft'] > 0 && $cl['thread_data']['post']['owner']['username'] == $me['username']) : ?>
												<div class = "form-info-label text-center text-danger mt-3">
													Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is about to expire in <?php echo $cl['thread_data']['post']['timeleft']; ?> days.
												</div>
											<?php else: ?>
												<div class = "form-info-label text-center text-danger mt-3">
													Your advertisement "<?php echo $cl['thread_data']['post']['company']; ?>" is expired!
												</div>
											<?php endif; ?>
											<h6 class="form-info-label text-center">
												<?php echo cl_translate('Continue a Monthly Ad Plan'); ?></h6>
											<div class="pb-2 form-info-label text-center">
												<?php echo cl_translate("Your ad will be displayed for one month. Ideal for short-term promotions."); ?>
											</div>
										</div>
										<div class="d-flex justify-content-center text-center c2action-single">
											<button type="button" class="btn btn-custom main-inline lg btn-block  w-50"
												v-on:click="selectPlan('monthly')">
												{{ selectMonthlyText }}
											</button>
										</div>
									</div>
								</div>
							</div>
							
							<h6 class="form-info-label text-center">
                                <?php echo cl_translate('Click above Plan to Select it'); ?>
                            </h6>
                             <!-- Show selected subscription if any -->
                            <div class="form-group" v-if="subscription_type">
                                <label><?php echo cl_translate("Selected Plan"); ?></label>
                                <input type="text" class="form-control" :value="subscription_type" readonly>
                            </div>
                            <!-- Subscription Section End -->
                    		<div class="form-group">
                    			<div class="form-tos">
                    				<div class="form-check">
                    					<input v-model="tos_agree" id="tos-agree" type="checkbox" class="form-check-input">
                    					<label for="tos-agree" class="form-check-label">
                    						<span>
                    							<?php echo cl_translate("By continuing, you agree to {@site_name@}",array(
                    								"site_name" => $cl["config"]["name"]
                    							)); ?>
                    						</span>
                    						<a href="<?php echo cl_link('terms_of_use'); ?>"><?php echo cl_translate("Terms of Use"); ?></a> <?php echo cl_translate("And"); ?> <a href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>
                    					</label>
                    				</div>
                    			</div>
                    		</div>
                    		<div class="form-group">
                    			<button v-if="submitting" disabled="true" class="btn btn-custom main-inline lg btn-block">
                    				<?php echo cl_translate("Please wait"); ?>
                    			</button>
                    			<button v-else v-bind:disabled="!is_subscribed || !tos_agree" type="button" class="btn btn-custom main-inline lg btn-block" @click="publish">
                					<?php echo cl_translate("Publish"); ?>
                    			</button>
                    		</div>
						<?php endif; ?>
				</div>
			</form>
		</div>
	</div>
	<!--keston plan add-->
	<div class="publication--thread-container">
		<div class="publication--thread-container-inner">
			<?php if (not_empty($cl['thread_data']['parent'])): ?>
				<div class="publication--thread-chain-holder">
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls" data-an="chain-list">
							<?php foreach ($cl['thread_data']['parent'] as $cl["li"]): ?>
								<?php echo cl_template('timeline/post'); ?>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
			<?php endif; ?>
			<div class="publication--thread-data-holder" data-an="thread-data">
				<div class="publication-data">
					<?php if (not_empty($cl['thread_data']['post']['me_blocked'])): ?>
						<div class="post-placeholder">
							<div class="d-flex flex-wn align-items-center">
								<div class="flex-item">
									<div class="icon">
										<?php echo cl_ikon("not-allowed"); ?>
									</div>
								</div>
								<div class="felx-item">
									<p>
										<?php echo cl_translate("This user ({@uname@}) has blocked you from accessing their posts", array(
											"uname" => cl_html_el("a", $cl['thread_data']['post']['owner']['username'], array("href" => $cl['thread_data']['post']['owner']['url']))
										)
										); ?>
									</p>
								</div>
							</div>
						</div>
					<?php elseif (empty($cl['thread_data']['post']['can_see'])): ?>
						<div class="post-placeholder">
							<div class="d-flex flex-wn align-items-center">
								<div class="flex-item">
									<div class="icon">
										<?php echo cl_ikon("eye-crossed"); ?>
									</div>
								</div>
								<div class="felx-item">
									<p>
										<?php echo cl_translate("Only followers of this user ({@uname@}) can see their posts", array(
											"uname" => cl_html_el("a", $cl['thread_data']['post']['owner']['username'], array("href" => $cl['thread_data']['post']['owner']['url']))
										)
										); ?>
									</p>
								</div>
							</div>
						</div>
					<?php else: ?>
						<?php if (not_empty($cl['thread_data']['post']['is_blocked'])): ?>
							<div class="soft-hidden-post"
								data-softhidden-post="<?php echo ($cl['thread_data']['post']['id']); ?>">
								<div class="d-flex align-items-center flex-wn">
									<div class="flex-item flex-grow-1">
										<p>
											<?php echo cl_translate('This is a message from the user you blocked'); ?>
										</p>
									</div>
									<div class="flex-item">
										<button class="btn btn-custom main-outline sm"
											onclick="SMColibri.show_post(<?php echo ($cl['thread_data']['post']['id']); ?>, 'blocked');">
											<?php echo cl_translate('View'); ?>
										</button>
									</div>
								</div>
							</div>
						<?php elseif ($cl['thread_data']['post']['is_reported']): ?>
							<div class="soft-hidden-post"
								data-softhidden-post="<?php echo ($cl['thread_data']['post']['id']); ?>">
								<div class="d-flex align-items-center flex-wn">
									<div class="flex-item flex-grow-1">
										<p>
											<?php echo cl_translate('This post is currently under review'); ?>
										</p>
									</div>
									<div class="flex-item">
										<button class="btn btn-custom main-outline sm"
											onclick="SMColibri.show_post(<?php echo ($cl['thread_data']['post']['id']); ?>, 'reported');">
											<?php echo cl_translate('View'); ?>
										</button>
									</div>
								</div>
							</div>
						<?php endif; ?>
						<div class="publication-data-inner ad-publication-data-inner">
							<div class="publisher-info ad-publisher-info">
								<div class="lp">
									<div class="avatar-holder">
										<img src="<?php echo ($cl['thread_data']['post']['owner']['avatar']); ?>"
											alt="Avatar">
									</div>
								</div>
								<div class="rp">
									<div class="flex-row" style="margin-left: -7px;">
										<a class="uname" href="<?php echo ($cl['thread_data']['post']['owner']['url']); ?>"
											data-uinfo-lbox="<?php echo ($cl['thread_data']['post']['user_id']); ?>"
											data-toggle="popover" data-placement="bottom">
											<b style="display: flex;     flex: 1;">
												<span class="user-name-holder">
													<?php echo ($cl['thread_data']['post']['owner']['name']); ?>
												</span>
												<p class="<?php if ($cl['thread_data']['post']['owner']['verified'] == '1') {
													echo ('verified-badge');
												} ?>" style="display:inline-block; margin-left:10px;"></p>
											</b>
											<span style="margin-left: -12px;">@
												<?php echo ($cl['thread_data']['post']['owner']['username']); ?>
											</span>
										</a>
										<button class="dropleft">
											<a href="#" class="dropdown-toggle icon" data-toggle="dropdown">
												<?php echo cl_ikon('pub-more'); ?>
											</a>
											<div class="dropdown-menu dropdown-icons">
												<a class="dropdown-item"
													href="<?php echo ($cl['thread_data']['post']['owner']['url']); ?>"
													data-spa="true">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_ikon('person'); ?>
													</span>
													<span class="flex-item">
														<?php echo ($cl['thread_data']['post']['owner']['name']); ?>
													</span>
												</a>
												<?php if (not_empty($cl['thread_data']['post']['can_delete'])): ?>
													<a class="dropdown-item col-red" href="javascript:void(0);">
														<span class="flex-item dropdown-item-icon">
															<svg viewBox="0 0 24 24" aria-hidden="true"
																class="r-9l7dzd r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr">
																<g>
																	<path
																		d="M16 6V4.5C16 3.12 14.88 2 13.5 2h-3C9.11 2 8 3.12 8 4.5V6H3v2h1.06l.81 11.21C4.98 20.78 6.28 22 7.86 22h8.27c1.58 0 2.88-1.22 3-2.79L19.93 8H21V6h-5zm-6-1.5c0-.28.22-.5.5-.5h3c.27 0 .5.22.5.5V6h-4V4.5zm7.13 14.57c-.04.52-.47.93-1 .93H7.86c-.53 0-.96-.41-1-.93L6.07 8h11.85l-.79 11.07zM9 17v-6h2v6H9zm4 0v-6h2v6h-2z">
																	</path>
																</g>
															</svg>
														</span>
														<span class="flex-item"
															onclick="SMColibri.delete_post('<?php echo $cl['thread_data']['post']['id']; ?>');">
															<?php echo cl_translate('Delete'); ?>
														</span>
													</a>
												<?php endif; ?>
												<a onclick="SMColibri.show_likes('<?php echo $cl['thread_data']['post']['id']; ?>');"
													class="dropdown-item" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_ikon('favourite'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Show likes'); ?>
													</span>
												</a>
												<a class="dropdown-item" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_ikon('bookmark'); ?>
													</span>
													<span class="flex-item"
														onclick="SMColibri.bookmark_post('<?php echo $cl['thread_data']['post']['id']; ?>', this);">
														<?php echo ((empty($cl['thread_data']['post']['has_saved'])) ? cl_translate('Bookmark') : cl_translate('Unbookmark')); ?>
													</span>
												</a>
												<a data-clipboard-text="<?php echo ($cl['thread_data']['post']['url']); ?>"
													class="dropdown-item clip-board-copy" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_ikon('copy'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Copy link'); ?>
													</span>
												</a>
												<div class="dropdown-divider"></div>
												<a onclick="SMColibri.share_post('<?php echo ($cl['thread_data']['post']['url']); ?>','<?php echo urlencode($cl['thread_data']['post']['url']); ?>');"
													class="dropdown-item" href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_ikon('share'); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Share'); ?>
													</span>
												</a>
											</div>
										</button>
									</div>
								</div>
							</div>
							<div class="publication-content">
								<?php if (not_empty($cl['thread_data']['post']['company'])): ?>
									<div class="publication-text mb-5">
										<h4>
											<?php echo $cl['thread_data']['post']['company']; ?>
										</h4>
										<p>
											<?php echo cl_rn2br($cl['thread_data']['post']['description']); ?>
										</p>
									</div>
								<?php endif; ?>
								<?php if (not_empty($cl['thread_data']['post']['og_data'])): ?>
								<?php $og_data = json_decode($cl['thread_data']['post']['og_data']); ?>
								
									
									<div class="publication-og-data">
										<div class="publication-og-data-inner embeded-iframe">
											<div class="og-image">
												<div class="lozad-media">
													<a href="<?php echo ($cl['thread_data']['post']['yt_url']); ?>"
														class="fbox-media">
														<img class="lozad"
															data-src="https://img.youtube.com/vi/<?echo $cl['thread_data']['post']['link_src']?>/hqdefault.jpg"
															alt="Video">
														<div class="og-icon">
															<span>
																<?php echo cl_ikon("play"); ?>
															</span>
														</div>
													</a>
												</div>
											</div>
											<div class="og-url-data">
												<h5>
													<?php 
													    echo json_decode($cl['thread_data']['post']['og_data'])->og_data->title 
													?>
												</h5>
												<p>
													<?php 
													echo json_decode($cl['thread_data']['post']['og_data'])->og_data->description 
													?>
												</p>
											</div>
										</div>
									</div>
									

								<?php elseif (isset($cl['thread_data']['post']['cover'])): ?>
									<div class="lozad-media">
										<div class="publication-image">
											<a href="<?php echo cl_get_media(fetch_or_get($cl['thread_data']['post']['cover'], '')); ?>"
												class="fbox-media">
												<img class="lozad"
													data-src="<?php echo cl_get_media(fetch_or_get($cl['thread_data']['post']['cover'], '')); ?>"
													alt="Picture">
											</a>
										</div>
									</div>
								<?php endif; ?>
							</div>

							<div class="publication-meta-info">
								<div class="posted-time">
									<?php echo cl_ikon('calendar'); ?>
									<time>
										<?php echo cl_date("h:i A - M d, Y", $cl['thread_data']['post']['time_raw'], true); ?>
									</time>
								</div>
								<?php if ($cl['thread_data']['post']['target'] == 'pub_reply' && not_empty($cl['thread_data']['post']['reply_to'])): ?>
									<div class="publication-target">
										<?php if (not_empty($cl['thread_data']['post']['reply_to']['is_owner'])): ?>
											<div class="post-reply">
												<span>
													<?php echo cl_translate('In response to your {@post_url@}', array(
														'post_url' => cl_html_el('a', cl_translate('post'), array(
															'href' => $cl['thread_data']['post']['reply_to']['thread_url'],
															'data-spa' => 'true'
														)
														)
													)
													); ?>
												</span>
											</div>
										<?php else: ?>
											<div class="post-reply">
												<span>
													<?php
													$text_temp = 'In response {@uname@} to his {@post_url@}';

													if ($cl['thread_data']['post']['reply_to']['gender'] == 'F') {
														$text_temp = 'In response {@uname@} to her {@post_url@}';
													}

													echo cl_translate($text_temp, array(
														'uname' => cl_html_el('a', $cl['thread_data']['post']['reply_to']['name'], array(
															'href' => $cl['thread_data']['post']['reply_to']['url'],
															'data-spa' => 'true'
														)
														),
														'post_url' => cl_html_el('a', cl_translate('publication'), array(
															'href' => $cl['thread_data']['post']['reply_to']['thread_url'],
															'data-spa' => 'true'
														)
														)
													)
													);
													?>
												</span>
											</div>
										<?php endif; ?>
									</div>
								<?php else: ?>
									<?php if (not_empty($cl['thread_data']['post']['is_owner']) && $cl['thread_data']['post']['target'] == 'publication'): ?>
										<div class="post-privacy">
											<button class="privacy-settings dropleft" type="button">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown">
													<?php if ($cl['thread_data']['post']['priv_wcr'] == "everyone"): ?>
														<span class="d-inline-flex align-items-center flex-wn">
															<span class="flex-item icon">
																<?php echo cl_ikon('language'); ?>
															</span>
															<span class="flex-item flex-grow-1 label">
																<?php echo cl_translate('Everyone can reply'); ?>
															</span>
														</span>
													<?php elseif ($cl['thread_data']['post']['priv_wcr'] == "mentioned"): ?>
														<span class="d-inline-flex align-items-center flex-wn">
															<span class="flex-item icon">
																<?php echo cl_ikon('ear'); ?>
															</span>
															<span class="flex-item flex-grow-1 label">
																<?php echo cl_translate('Only mentioned people'); ?>
															</span>
														</span>
													<?php else: ?>
														<span class="d-inline-flex align-items-center flex-wn">
															<span class="flex-item icon">
																<?php echo cl_ikon('people'); ?>
															</span>
															<span class="flex-item flex-grow-1 label">
																<?php echo cl_translate('Only my followers'); ?>
															</span>
														</span>
													<?php endif; ?>
												</a>
												<div class="dropdown-menu dropdown-icons">
													<a class="dropdown-item" href="javascript:void(0);"
														onclick="SMColibri.post_privacy('everyone', <?php echo $cl['thread_data']['post']['id']; ?>);">
														<span class="flex-item dropdown-item-icon">
															<?php echo cl_ikon('language'); ?>
														</span>
														<span class="flex-item ">
															<?php echo cl_translate('Everyone can reply'); ?>
														</span>
													</a>
													<a class="dropdown-item" href="javascript:void(0);"
														onclick="SMColibri.post_privacy('mentioned', <?php echo $cl['thread_data']['post']['id']; ?>);">
														<span class="flex-item dropdown-item-icon">
															<?php echo cl_ikon('ear'); ?>
														</span>
														<span class="flex-item ">
															<?php echo cl_translate('Only mentioned people'); ?>
														</span>
													</a>
													<a class="dropdown-item" href="javascript:void(0);"
														onclick="SMColibri.post_privacy('followers', <?php echo $cl['thread_data']['post']['id']; ?>);">
														<span class="flex-item dropdown-item-icon">
															<?php echo cl_ikon('people'); ?>
														</span>
														<span class="flex-item ">
															<?php echo cl_translate('Only my followers'); ?>
														</span>
													</a>
												</div>
											</button>
										</div>
									<?php endif; ?>
								<?php endif; ?>
							</div>

							<div class="post-list-advert__ctrl">
								<?php 
								// echo '<pre>';print_r($cl['thread_data']['post']['is_owner']);'</pre>';die;
								//if (isset($cl['thread_data']['post']['is_conversed'])):
									if (not_empty($cl['thread_data']['post']['is_owner']) || not_empty($cl['thread_data']['post']['is_conversed'])): ?>
										<a target="_blank" href="<?php echo $cl['thread_data']['post']['target_url']; ?>" class="block-link">
											<button class="btn target-url-btn btn-custom main-outline lg btn-block pt-prevent-click">
												<?php echo $cl['thread_data']['post']['cta']; ?>
											</button>
										</a>
									<?php else: ?>
										<button onclick="SMColibri.ad_conversion(this);" data-ad-id="<?php echo $cl['thread_data']['post']['id']; ?>" data-ad-url="<?php echo $cl['thread_data']['post']['target_url']; ?>" class="btn target-url-btn btn-custom main-outline lg btn-block pt-prevent-click">
											<?php echo $cl['thread_data']['post']['cta']; ?>
										</button>
									<?php endif;
								//endif;  ?>
							</div>
							<div class="publication-footer-ctrls">
								<?php if (not_empty($cl['thread_data']['can_reply'])): ?>
									<button class="ctrls-item"
										onclick="SMColibri.pub_reply('<?php echo $cl['thread_data']['post']['id']; ?>');">
										<span class="icon">
											<?php echo cl_ikon('chat-post'); ?>
										</span>
										<span class="num" data-an="pub-replys-total">
											<?php echo $cl['thread_data']['post']['replys_count']; ?>
										</span>
									</button>
								<?php else: ?>
									<button class="ctrls-item" disabled="true">
										<span class="icon">
											<?php echo cl_ikon('chat-post'); ?>
										</span>
										<span class="num" data-an="pub-replys-total">
											<?php echo $cl['thread_data']['post']['replys_count']; ?>
										</span>
									</button>
								<?php endif; ?>

								<?php if (empty($cl['thread_data']['post']['has_liked'])): ?>
									<button class="ctrls-item"
										onclick="SMColibri.like_post('<?php echo $cl['thread_data']['post']['id']; ?>', this);">
										<span class="icon">
											<?php echo cl_ikon('likes'); ?>
										</span>
										<span class="num" data-an="likes-count">
											<?php echo $cl['thread_data']['post']['likes_count']; ?>
										</span>
									</button>
								<?php else: ?>
									<button class="ctrls-item liked"
										onclick="SMColibri.like_post('<?php echo $cl['thread_data']['post']['id']; ?>', this);">
										<span class="icon">
											<?php echo cl_ikon('likes'); ?>
										</span>
										<span class="num" data-an="likes-count">
											<?php echo $cl['thread_data']['post']['likes_count']; ?>
										</span>
									</button>
								<?php endif; ?>
								<button onclick="SMColibri.repost('<?php echo $cl['thread_data']['post']['id']; ?>', this);"
									class="ctrls-item" data-an="repost-ctrl">
									<span class="icon">
										<?php echo cl_ikon('repost'); ?>
									</span>
									<span class="num" data-an="reposts-count">
										<?php echo $cl['thread_data']['post']['reposts_count']; ?>
									</span>
								</button>
								<button class="ctrls-item"
									onclick="SMColibri.share_post('<?php echo $cl['thread_data']['post']['url']; ?>','<?php echo urlencode($cl['thread_data']['post']['url']); ?>');">
									<span class="icon">
										<?php echo cl_ikon('share'); ?>
									</span>
								</button>
                                <!--Hide reply button   2025.04.11 by keston-->
								<!--<div class="reply_button">-->
								<!--	<button-->
								<!--		onclick="SMColibri.pub_reply('<?php echo $cl['thread_data']['post']['id']; ?>');"-->
								<!--		class="btn-custom reply main-inline md post-pub-btn">-->
								<!--		<?php echo cl_translate("Tweet Your Reply"); ?> </button>-->
								<!--</div>-->
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
			<?php if (not_empty($cl["gads_horiz"])): ?>
				<div class="cl-google-ads centered">
					<?php echo $cl["gads_horiz"]; ?>
				</div>
			<?php endif; ?>
			<!--Hide reply thread holder 2025.04.11 by keston-->
			<div class="publication--thread-replys-holder">
				<?php if (not_empty($cl['thread_data']['next'])): ?>
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls" data-an="replys-list">
							<?php foreach ($cl['thread_data']['next'] as $cl["li"]): ?>
								<?php if (empty($cl["li"]["replys"])): ?>
									<?php echo cl_template('timeline/post'); ?>
								<?php else: ?>
									<div class="timeline-posts-ls-group">
										<div class="timeline-posts-ls-group-inner">
											<?php echo cl_template('timeline/post'); ?>

											<?php
											$parent_thread = $cl['li'];
											$post_replys = $parent_thread['replys'];
											$post_replys = array_reverse($post_replys);

											foreach ($post_replys as $cl['li']) {
												echo cl_template('timeline/post');
											}
											?>
										</div>

										<a class="show-thread" href="<?php echo ($parent_thread["url"]); ?>" data-spa="true">
											<span class="txt-label">
												(
												<?php echo ($parent_thread["replys_count"]); ?>)
												<?php echo cl_translate("Show this thread"); ?>
											</span>
											<span class="icon">
												<?php echo cl_ikon('arrow-right'); ?>
											</span>
										</a>
									</div>
								<?php endif; ?>
							<?php endforeach; ?>
						</div>
					</div>
					<?php if (count($cl['thread_data']['next']) == 30): ?>
						<div class="load-more">
							<button class="btn btn-custom main-outline lg" data-an="load-more">
								<?php echo cl_translate("Show more"); ?>
							</button>
						</div>
					<?php else: ?>
						<div class="load-more">
							<button disabled="true" class="btn btn-custom main-outline lg" data-an="load-more">
								<?php echo cl_translate("That is all for now!"); ?>
							</button>
						</div>
					<?php endif; ?>
				<?php else: ?>
					<div class="no-thread-replys">
						<div class="icon">
							<?php echo cl_ikon('chat-post'); ?>
						</div>
						<div class="pl-message">
							<h4>
								<?php echo cl_translate("No replys yet!"); ?>
							</h4>
							<p>
								<?php echo cl_translate("It seems that this publication does not yet have any comments. In order to respond to this publication from {@publisher_name@}, click on at the button above", array(
									"svg_icon" => cl_html_el("span", cl_ikon('chat-post')),
									"publisher_name" => cl_html_el('a', $cl['thread_data']['post']['owner']['name'], array(
										"href" => $cl['thread_data']['post']['owner']['url'],
										"data-spa" => "true"
									)
									)
								)
								); ?>
							</p>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<?php echo cl_template('thread/scripts/app_master_script'); ?>
</div>

<style>
	body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-header div.lp div.nav-link-holder {
		line-height: 20px;
		display: inline-flex;
		margin: ;
		vertical-align: middle;
		justify-content: center;
		align-items: center;
	}

	.reply_button button.btn-custom.reply {
		max-height: 36px !important;
		min-height: 36px !important;
		color: rgb(255, 255, 255);
		font-weight: 700;
		-moz-box-align: center;
		align-items: center;
		-moz-box-pack: center;
		justify-content: center;
		font-size: 15px !important;
		display: flex;
		background-color: rgb(29, 155, 240) !important;
		transition-property: background-color, box-shadow !important;
		border-color: rgba(0, 0, 0, 0) !important;
		padding-left: 16px !important;
		padding-right: 16px !important;
		border-width: 1px;
		border-style: solid;
	}
</style>