<div class="timeline-container" data-app="thread">
    <div class="timeline-header__topline">
        <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
    </div>
    <div class="publication--thread-container">
        <div class="publication--thread-container-inner">
            <!--<?php if (not_empty($cl['thread_data']['parent'])) : ?>-->
            <!--    <div class="publication--thread-chain-holder">-->
            <!--        <div class="timeline-posts-container">-->
            <!--            <div class="timeline-posts-ls" data-an="chain-list">-->
            <!--                <?php foreach ($cl['thread_data']['parent'] as $cl["li"]) : ?>-->
            <!--                    <?php echo cl_template('timeline/post'); ?>-->
            <!--                <?php endforeach; ?>-->
            <!--            </div>-->
            <!--        </div>-->
            <!--    </div>-->
            <!--<?php endif; ?>-->
            <!--////////////////////////////////////////////-->
			<?php if (not_empty($cl["random_ads_main"])): ?>
				<div class="timeline-posts-container">
					<div class="timeline-posts-ls szHomeTimeline" data-an="entry-list">
						<?php foreach ($cl["random_ads_main"] as $cl['li']): ?>
							<?php echo cl_template('timeline/right_ad'); ?>
						<?php endforeach; ?>
					</div>
				</div>
			<?php else: ?>
                <div class="no-ads-message">
                    <p>No ads available.</p>
                </div>
			<?php endif; ?>
			
			<!--///////////////////////-->


            
        </div>
    </div>

    <?php echo cl_template('thread/scripts/app_master_script'); ?>
</div>

<style>
    .left-sb-container.sidebar {
        display: none !important;
    }
    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container {
        padding-top: 0 !important;
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container {
        margin-top: 10px;
    }

    body div.mobile-bottom-navbar div.mobile-bottom-navbar-inner {
        display: none;
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publication-data div.publication-data-inner div.publisher-info div.lp a span {
        max-width: 80px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        display: inline-flex;
        vertical-align: middle;
    }

    .reply_button {
        display: flex;
        justify-content: center;
        align-content: center;
        padding: 10px;
        padding-bottom: 0px;
    }

    .reply_button button.btn-custom.reply {
        max-height: 36px !important;
        min-height: 36px !important;
        color: rgb(255, 255, 255);
        font-weight: 700;
        -moz-box-align: center;
        align-items: center;
        -moz-box-pack: center;
        justify-content: center;
        font-size: 15px !important;
        display: flex;
        background-color: rgb(29, 155, 240) !important;
        transition-property: background-color, box-shadow !important;
        border-color: rgba(0, 0, 0, 0) !important;
        padding-left: 16px !important;
        padding-right: 16px !important;
        border-width: 1px;
        border-style: solid;
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publication-data div.publication-data-inner div.publisher-info div.lp a span.user-name-holder {
        max-width: 60px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        display: inline-flex;
        vertical-align: middle;
    }

    div.lp span.posted-time {
        line-height: 14px;
        
    }

    @media (max-width: 1199.98px) {
        body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publisher-avatar {
            width: 48px;
            flex-basis: 48px;
            max-width: 48px;
            min-width: 48px;
        }

        body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publisher-avatar div.avatar-holder {
            width: 48px;
            height: 48px;
        }
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publication-data div.publication-data-inner div.publisher-info div.lp a span.user-name-holder.verified-badge {
        vertical-align: middle;
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publication-data div.publication-data-inner div.publisher-info div.lp a span.user-name-holder.verified-badge::after {
        height: 1px;
    }

    body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container div.timeline-posts-ls div.post-list-item div.post-list-item-content div.publication-data div.publication-data-inner div.publication-footer-ctrls {
        padding-right: 0px;
    }
</style>
<style>
	 .guest_bottom {
		display: none!important;
	}
</style>