<script>
	"use strict";

	var offset = 30;
	const post_id = getUrlParameter('post_id');

	jQuery(document).ready(function($) {	
		var _app    = $('div[data-app="feed"]');
		var feed_ls = _app.find('[data-an="entry-list"]');

		_app.find('button[data-an="load-more"]').on('click', function(event) {
		   
		    szLoadMoreHome(event);
		});

	});
	
	function szLoadMoreHome() {
	    	event.preventDefault();
			
			var Btnself = $('.szLoadMoreBtn');
			

			$.ajax({
				// url: "<?php //echo cl_link("native_api/feed/load_more"); ?>",
				//https://p-tweets.com/talk/native_api/explore/load_more
				url: "<?php echo cl_link("native_api/explore/load_more"); ?>",
				type: 'GET',
				dataType: 'json',
				data: {
					offset: offset,
					post_id: post_id,
					type: "posts",
				},
				beforeSend: function(){
					Btnself.attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
				}
			}).done(function(data) {
			   console.log("home",data);
				if (data.status == 200) {
				// 	feed_ls.append(data.html);
					$('.szHomeTimeline').append(data.html);

					Btnself.removeAttr('disabled').text("<?php echo cl_translate("Show more"); ?>");

					offset += 30;
				}

				else {
					Btnself.text("<?php echo cl_translate("That is all for now!"); ?>");
				}
			});
	}
	
	function getUrlParameter(name) {
		const urlParams = new URLSearchParams(window.location.search);
		return urlParams.get(name);
	}
	
</script>