<div class="search-result__list-item search-result__list-item_user">
<?php $url = isset($cl['li']['url']) ? $cl['li']['url'] : '#'; ?>

    <a href="<?php echo $url; ?>" data-spa="true">
        <div class="result-item-data">
            <div class="result-item-data__avatar">
                <div class="avatar">
                    <img src="<?php echo($cl['li']['owner']['avatar']); ?>" alt="Avatar">
                </div>
            </div>
            <div class="result-item-data__data">
                <div class="result-item-data__topline">
					<span class="user-name-holder">
						<span class="user-name-holder__name">
							<?php echo($cl['li']['owner']['name']); ?>
						</span>

						<?php if ($cl['li']['owner']['verified'] == '1'): ?>
                            <span class="user-name-holder__badge">
								<?php echo cl_icon("verified_user_badge"); ?>
							</span>
                        <?php endif; ?>
                        <span style="color: var(--cl-secondary-text-color)">
                             @<?php echo($cl['li']['owner']['username']); ?>
                        </span>
					</span>
                </div>
                <div class="result-item-data__botline" style="color: var(--cl-primary-text-color);font-size: 16px;padding-top: 7px;">
                    <?= strip_tags($cl['li']['text'] ?? '') ?>
                </div>
            </div>
        </div>
    </a>
</div>
